- hosts: metagroup
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: copy nginx.conf
      template:
        src: ../sources/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: copy index.html
      template:
        src: ../sources/index.html
        dest: /usr/share/nginx/html/index.html

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
