- hosts: metagroup
  vars:
    - nginx_port: 8080
    - root_dir: /var/tmp/www
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    
    - name: create root dir
      file:
        path: "{{ root_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: template nginx.conf
      template:
        src: ../sources/nginx.conf
        dest: "{{ root_dir }}/nginx.conf"
      notify: restart nginx

    - name: template index.html
      template:
        src: ../sources/index.html
        dest: "{{ root_dir }}/index.html"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
