- hosts: webservers
  vars:
    - nginx_port: 8080
    - root_dir: /var/tmp/www
    - deployment_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: install cowsay
      apt:
        name: cowsay
        state: present

    - name: run cowsay
      shell: cowsay "This is {{ server_name }}"
      register: cowsay_result
    
    - name: create root dir
      file:
        path: "{{ root_dir }}"
        state: directory
        owner: www-data
        group: www-data

    - name: template nginx.conf
      template:
        src: ../sources/nginx.conf
        dest: "/etc/nginx/nginx.conf"
      notify: restart nginx

    - name: template index.html
      template:
        src: ../sources/index.html
        dest: "/usr/share/nginx/html/index.html"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
