---
# tasks file for ./roles/create_user
- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: create users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    createhome: yes
  loop: "{{ users }}"
  become: yes

- name: update users git configs
  template:
    src: ./files/.gitconfig
    dest: "/home/{{ item }}/.gitconfig"
  loop: "{{ users }}"
